# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
    ]
