# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
